version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Порт, на котором будет доступно ваше приложение
    environment:
      DB_URL: jdbc:postgresql://db:5432/animals  # URL для подключения к базе данных
      DB_USERNAME: postgres                              # Имя пользователя
      DB_PASSWORD: root                             # Пароль
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: animals  # Имя базы данных
      POSTGRES_USER: postgres       # Имя пользователя
      POSTGRES_PASSWORD: root    # Пароль
    ports:
      - "5432:5432"  # Порт, на котором будет доступна база данных